In [2]:
# Import library
import pandas as pd

# Load dataset
# Please make sure 'ApexPlanet_DataAnalytics_Dataset.xlsx' is uploaded to the /content/ directory.
df = pd.read_excel('/content/ApexPlanet_DataAnalytics_Dataset.xlsx')

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [3]:
#Display First 5 Rows
print("\nFirst 5 Rows:")
display(df.head())

First 5 Rows:

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [4]:
#Display Last 5 Rows
print("\nLast 5 Rows:")
display(df.tail())

Last 5 Rows:

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
995,ORD100997,2025-11-07,CUST6410,Customer_301,61.0,Male,Gaya,Laptop,Electronics,9,35405.54,318649.86
996,ORD100998,2025-09-03,CUST7618,Customer_154,25.0,Male,Gaya,Shoes,Fashion,5,18454.65,92273.25
997,ORD100999,2025-09-30,CUST9544,Customer_140,62.0,Female,Hyderabad,Laptop,Electronics,9,12971.59,116744.31
998,ORD101000,2025-02-21,CUST9501,Customer_241,NaN,Male,Delhi,Mobile,Electronics,9,2879.01,25911.09
999,ORD101001,2025-04-23,CUST2714,Customer_98,58.0,Female,Gaya,Chair,Furniture,9,22493.87,202444.83

In [5]:
#Shape of Dataset
print("Rows and Columns :", df.shape)

Rows and Columns : (1000, 12)

In [6]:
#Column Names
print(df.columns)

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Total_Sales'],
      dtype='object')

In [7]:
#Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [8]:
#Summary Statistics
print("\nNumerical Summary")
display(df.describe())

Numerical Summary

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

In [9]:
#For categorical columns
print("\nCategorical Summary")
display(df.describe(include='object'))

Categorical Summary

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,City,Product,Category
count,1000,1000,1000,1000,1000,987,1000,1000
unique,992,342,947,425,2,8,6,5
top,ORD100050,2025-04-16,CUST2515,Customer_359,Male,Patna,Mobile,Electronics
freq,9,10,3,8,511,135,184,354

In [10]:
print("\nOverall Summary")
display(df.describe(include='all'))

Overall Summary

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
count,1000,1000,1000,1000,980.000000,1000,987,1000,1000,1000.000000,1000.000000,1000.000000
unique,992,342,947,425,NaN,2,8,6,5,NaN,NaN,NaN
top,ORD100050,2025-04-16,CUST2515,Customer_359,NaN,Male,Patna,Mobile,Electronics,NaN,NaN,NaN
freq,9,10,3,8,NaN,511,135,184,354,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,41.360204,NaN,NaN,NaN,NaN,5.435000,25486.783410,139399.439650
std,NaN,NaN,NaN,NaN,13.822597,NaN,NaN,NaN,NaN,2.838632,14179.402361,114100.051546
min,NaN,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,1.000000,145.780000,437.340000
25%,NaN,NaN,NaN,NaN,30.000000,NaN,NaN,NaN,NaN,3.000000,13895.722500,47066.632500
50%,NaN,NaN,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,5.000000,25398.740000,108594.025000
75%,NaN,NaN,NaN,NaN,54.000000,NaN,NaN,NaN,NaN,8.000000,37512.382500,203722.882500
max,NaN,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,10.000000,49997.530000,493677.500000

In [11]:
#Check Missing Values
print("\nMissing Values")
display(df.isnull().sum())

Missing Values

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [12]:
#Check Duplicate Rows
print("\nDuplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [13]:
#Data Types
print("\nData Types")
display(df.dtypes)

Data Types

Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

In [14]:
#Data Dictionary

In [15]:
#| Column        | Data Type | Description                | Business Relevance      |
#| ------------- | --------- | -------------------------- | ----------------------- |
#| Order_ID      | Integer   | Unique order identifier    | Tracks every order      |
#| Order_Date    | Date      | Date when order was placed | Sales trend analysis    |
#| Customer_ID   | Integer   | Unique customer ID         | Identify customers      |
#| Customer_Name | Object    | Customer name              | Customer records        |
#| Age           | Numeric   | Customer age               | Customer segmentation   |
#| Gender        | Object    | Customer gender            | Demographic analysis    |
#| City          | Object    | Customer city              | Regional sales analysis |
#| Product       | Object    | Product purchased          | Product performance     |
#| Category      | Object    | Product category           | Category-wise sales     |
#| Quantity      | Integer   | Units purchased            | Demand analysis         |
#| Unit_Price    | Float     | Price of one unit          | Pricing analysis        |
#| Total_Sales   | Float     | Total revenue from order   | Revenue analysis        |

In [16]:
data_dict = pd.DataFrame({
    'Column': ['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name',
               'Age', 'Gender', 'City', 'Product', 'Category',
               'Quantity', 'Unit_Price', 'Total_Sales'],

    'Data Type': ['Integer', 'Date', 'Integer', 'Object',
                  'Numeric', 'Object', 'Object', 'Object',
                  'Object', 'Integer', 'Float', 'Float'],

    'Description': [
        'Unique order identifier',
        'Date when order was placed',
        'Unique customer ID',
        'Customer name',
        'Customer age',
        'Customer gender',
        'Customer city',
        'Product purchased',
        'Product category',
        'Units purchased',
        'Price per unit',
        'Total revenue from the order'
    ],

    'Business Relevance': [
        'Tracks every order',
        'Sales trend analysis',
        'Identify customers',
        'Customer records',
        'Customer segmentation',
        'Demographic analysis',
        'Regional sales analysis',
        'Product performance',
        'Category-wise sales',
        'Demand analysis',
        'Pricing analysis',
        'Revenue analysis'
    ]
})

data_dict

,Column,Data Type,Description,Business Relevance
0,Order_ID,Integer,Unique order identifier,Tracks every order
1,Order_Date,Date,Date when order was placed,Sales trend analysis
2,Customer_ID,Integer,Unique customer ID,Identify customers
3,Customer_Name,Object,Customer name,Customer records
4,Age,Numeric,Customer age,Customer segmentation
5,Gender,Object,Customer gender,Demographic analysis
6,City,Object,Customer city,Regional sales analysis
7,Product,Object,Product purchased,Product performance
8,Category,Object,Product category,Category-wise sales
9,Quantity,Integer,Units purchased,Demand analysis
10,Unit_Price,Float,Price per unit,Pricing analysis
11,Total_Sales,Float,Total revenue from the order,Revenue analysis

In [17]:
#Basic Business Understanding
print("Number of Orders :", len(df))
print("Number of Customers :", df['Customer_ID'].nunique())
print("Number of Products :", df['Product'].nunique())
print("Categories :", df['Category'].unique())

Number of Orders : 1000
Number of Customers : 947
Number of Products : 6
Categories : ['Grocery' 'Education' 'Electronics' 'Fashion' 'Furniture']

In [18]:
#Check Unique Values
for col in df.columns:
    print(f"\n{col}")
    print(df[col].unique()[:10])

Order_ID
['ORD100002' 'ORD100003' 'ORD100004' 'ORD100005' 'ORD100006' 'ORD100007'
 'ORD100008' 'ORD100009' 'ORD100010' 'ORD100011']

Order_Date
['2025-02-25' '2025-10-14' '2025-05-13' '2025-12-02' '2025-11-20'
 '2025-12-31' '2025-12-05' '2025-11-21' '2025-04-16' '2025-05-05']

Customer_ID
['CUST5529' 'CUST3127' 'CUST8887' 'CUST2515' 'CUST4796' 'CUST3952'
 'CUST1758' 'CUST9622' 'CUST9770' 'CUST1312']

Customer_Name
['Customer_227' 'Customer_182' 'Customer_487' 'Customer_470'
 'Customer_380' 'Customer_71' 'Customer_335' 'Customer_224' 'Customer_494'
 'Customer_40']

Age
[30. 63. 62. 65. 44. 40. 61. 35. 41. 51.]

Gender
['Female' 'Male']

City
['Bengaluru' 'Kolkata' 'Hyderabad' 'Patna' 'Mumbai' 'Delhi' 'Gaya' 'Pune'
 nan]

Product
['Rice' 'Book' 'Mobile' 'Laptop' 'Shoes' 'Chair']

Category
['Grocery' 'Education' 'Electronics' 'Fashion' 'Furniture']

Quantity
[ 7  5  8  9 10  6  3  1  2  4]

Unit_Price
[ 2829.77 27906.16 37491.06 28541.36 14036.59 35947.47 49997.53  9488.83
 19488.23 18024.34]

Total_Sales
[ 19808.39 139530.8  299928.48 256872.24 140365.9  323527.23 299985.18
  28466.49 116929.38 144194.72]

In [19]:
# Detect Outliers
numeric_columns = df.select_dtypes(include=['int64','float64']).columns

print("\nOutlier Detection")
for col in numeric_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col}: {len(outliers)} outliers")

Outlier Detection
Age: 0 outliers
Quantity: 0 outliers
Unit_Price: 0 outliers
Total_Sales: 19 outliers

In [20]:
#Dataset Overview
print("Dataset Shape :", df.shape)

print("\nColumn Names")
print(df.columns.tolist())

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows :", df.duplicated().sum())

print("\nData Types")
print(df.dtypes)

Dataset Shape : (1000, 12)

Column Names
['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Total_Sales']

Missing Values
Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

Duplicate Rows : 0

Data Types
Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

In [21]:
# Standardize Column Names first
df.columns = df.columns.str.lower().str.replace(" ", "_")

# Fill missing age values using median of each category
df['age'] = df.groupby('category')['age'].transform(lambda x: x.fillna(x.median()))

# Fill missing city values using the most frequent city
df['city'] = df['city'].fillna(df['city'].mode()[0])

# Remove duplicate rows
df = df.drop_duplicates()

In [22]:
print("\nMissing Values After Cleaning")
display(df.isnull().sum())

Missing Values After Cleaning

order_id         0
order_date       0
customer_id      0
customer_name    0
age              0
gender           0
city             0
product          0
category         0
quantity         0
unit_price       0
total_sales      0
dtype: int64

In [23]:
print("\nDuplicate Rows After Cleaning")
print(df.duplicated().sum())

Duplicate Rows After Cleaning
0

In [24]:
print("\nCleaned Dataset")
display(df.head())

Cleaned Dataset

,order_id,order_date,customer_id,customer_name,age,gender,city,product,category,quantity,unit_price,total_sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [25]:
# Save the cleaned dataset
df.to_excel("Cleaned_ApexPlanet_DataAnalytics_Dataset.xlsx", index=False)

print("Cleaned dataset created successfully!")

from google.colab import files
files.download("Cleaned_ApexPlanet_DataAnalytics_Dataset.xlsx")

Cleaned dataset created successfully!